services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-server:dev
    container_name: nestjs-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      # 覆盖 .env 里的 host，改成 Docker 容器名
      DB_HOST: mysql-dev
      DB_PORT: 3306
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      PORT: 3001
      NODE_ENV: production
    networks:
      - web-net

networks:
  app-net:
    external: true
    name: web-net
